DROP TABLE IF EXISTS films  CASCADE;
DROP TABLE IF EXISTS films_ganres  CASCADE;
DROP TABLE IF EXISTS friendships  CASCADE;
DROP TABLE IF EXISTS likes  CASCADE;
DROP TABLE IF EXISTS ratings  CASCADE;
DROP TABLE IF EXISTS users  CASCADE;
DROP TABLE IF EXISTS genres  CASCADE;